INTERNAL_MAIL_SERVER = ''
INTERNAL_MAIL_USERNAME = ''
INTERNAL_MAIL_PASSWORD = ''
INTERNAL_MAIL_PORT = 587


HIPCHAT_TOKEN = ''
HIPCHAT_ROOMID = 0
HIPCHAT_SENDER = ''

ERROR_MAIL_SENDER_EMAIL = ''
ERROR_MAIL_RECIPIENT_EMAIL = ''

CACHE_ENABLED = False
CACHE_URL = '127.0.0.1:11211'
CACHE_LOCK_DIR = '/tmp/cache/lock'

MAIL_URL_ROOT = 'localhost'

DATABASE = ''
DATABASE_URI = 'mysql://root@localhost/'\
               '%s?unix_socket=/var/run/mysqld/mysqld.sock' % DATABASE

##
# Social Network

FACEBOOK_CLIENT_ID = ''
FACEBOOK_CLIENT_SECRET = ''


TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''

INSTAGRAM_CLIENT_ID = ''
INSTAGRAM_CLIENT_SECRET = ''
